spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        ## service1
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1

        ## Service2
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
server:
  port: 8081

spring:
  cloud:
    consul:
      discovery:
        fail-fast: true
      host: localhost
      port: 8500
    gateway:
      routes:
       - id: consul-service
         uri: lb://consul-application
         predicates:
         - Path=/consul/**